"use client"
import React, { useEffect, useState, useRef, useCallback } from 'react'
import { useParams, useSearchParams } from 'next/navigation'
import axios from 'axios'
import PlaygroundHeader from '../_components/PlaygroundHeader'
import ChatSection from '../_components/ChatSection'
import WebsiteDesign from '../_components/WebsiteDesign'
import Settings from '../_components/Settings'


export type Frame = {
  projectId: string;
  frameId: string;
  chatMessages: Messages[];
  designCode: string;
}
export type Messages = {
  role: string;
  content: string;
  image?: string;
}


const Prompt = `{user_input}

Instructions:

1. If the user input is explicitly asking to generate code, design, or HTML/CSS/JS output (e.g., "Create a landing page", "Build a dashboard", "Generate HTML Tailwind CSS code"), then:

  - Generate a complete website project using HTML, CSS, JavaScript, React, JSON, backend, and database files when they are requested or needed.
   - Use a modern design with **{theme_color} as the primary color theme**.
  - Always include a browser-previewable \`index.html\` file.
   - Make it fully responsive for all screen sizes.
   - All primary components must match the theme color.
   - Add proper padding and margin for each element.
   - Use real high-resolution Unsplash image URLs (e.g. https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80 for tech, https://images.unsplash.com/photo-1523275335684-37898b6baf30 for products, https://images.unsplash.com/photo-1534528741775-53994a69daeb for avatars). Never use grey placehold.co images.
   - Add alt tag describing the image.
   - Use the following libraries/components where appropriate:
     - FontAwesome icons (fa fa-)
     - Flowbite UI components: buttons, modals, forms, tables, tabs, alerts, cards, dialogs, dropdowns, accordions, etc.
     - Chart.js for charts & graphs
     - Swiper.js for sliders/carousels
     - Tippy.js for tooltips & popovers
   - Include interactive components like modals, dropdowns, and accordions.
   - Ensure proper spacing, alignment, hierarchy, and theme consistency.
   - Ensure charts are visually appealing and match the theme color.
   - Header menu options should be spread out and not connected.
   - Do not include broken links.
  - Generate only the requested website. Never recreate or include the AI Website Generator application, PlaygroundHeader, ChatSection, WebsiteDesign, Settings panel, sidebar, toolbar, version selector, Save button, Preview/Code controls, or Export ZIP button.
  - The generated output is rendered inside an isolated preview iframe, so it must contain only the website requested by the user and must never render another Playground page or nested website generator.
   - Do not add any extra explanation before or after the files.
   - IMPORTANT: Return every project file using exactly this format, one file after another:
     --- FILE: index.html ---
     <file contents>
     --- FILE: css/styles.css ---
     <file contents>
     --- FILE: js/main.js ---
     <file contents>
  - Use sensible folders such as \`css/\`, \`js/\`, \`src/\`, \`server/\`, \`api/\`, \`database/\`, and \`config/\`. Keep HTML, CSS, JavaScript, React, JSON, backend, and database code in separate files. Never put the whole project into one HTML file.

2. If the user input is **general text or greetings** (e.g., "Hi", "Hello", "How are you?") **or does not explicitly ask to generate code**, then:

   - Respond with a simple, friendly text message instead of generating any code.

Example:

- User: "Hi" → Response: "Hello! How can I help you today?"
- User: "Build a responsive landing page with Tailwind CSS" → Response: [Generate full HTML code as per instructions above]`;


function PlaygroundPage() {
  const { projectId } = useParams();
  const searchParams = useSearchParams();
  const frameId = searchParams.get('frameId');
  const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Messages[]>([]);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const hasAutoGenerated = useRef(false);
  const [selectedModel, setSelectedModel] = useState('gemini-3.6-flash');
  const [selectedTheme, setSelectedTheme] = useState('blue');
  const [showSettings, setShowSettings] = useState(false);

  // ---- Undo / Redo history for generatedCode ----
  const codeHistoryRef = useRef<string[]>(['']);
  const historyIndexRef = useRef<number>(0);
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);

  const commitCodeToHistory = (code: string) => {
    if (codeHistoryRef.current[historyIndexRef.current] === code) return;
    codeHistoryRef.current = codeHistoryRef.current.slice(0, historyIndexRef.current + 1);
    codeHistoryRef.current.push(code);
    historyIndexRef.current = codeHistoryRef.current.length - 1;
    setCanUndo(historyIndexRef.current > 0);
    setCanRedo(false);
  };

  const handleUndo = () => {
    if (historyIndexRef.current <= 0) return;
    historyIndexRef.current -= 1;
    setGeneratedCode(codeHistoryRef.current[historyIndexRef.current]);
    setCanUndo(historyIndexRef.current > 0);
    setCanRedo(true);
  };

  const handleRedo = () => {
    if (historyIndexRef.current >= codeHistoryRef.current.length - 1) return;
    historyIndexRef.current += 1;
    setGeneratedCode(codeHistoryRef.current[historyIndexRef.current]);
    setCanUndo(true);
    setCanRedo(historyIndexRef.current < codeHistoryRef.current.length - 1);
  };
  
  const SendMessage = async(message: string, skipAddUserMessage: boolean = false, image?: string) => {
    setLoading(true);
    setGeneratedCode(''); // Reset generated code for new generation

    //Add User Message (if not already in messages)
    if(!skipAddUserMessage) {
      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'user', content: message }]);
    }

    // Build messages array: send full history without the last message, then add it with the prompt
    const messagesWithoutLast = skipAddUserMessage ? messages.slice(0, -1) : messages;
    const finalPrompt = Prompt?.replace('{user_input}', message).replace('{theme_color}', selectedTheme);
    const formattedMessages = [
      ...messagesWithoutLast,
      { role: 'user', content: finalPrompt }
    ];

    const response = await fetch('/api/ai-model', {
      method:'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body:JSON.stringify({
        messages: formattedMessages,
        modelName: selectedModel,
        image: image || undefined
      })
    });

    // Check if credits ran out (403) or other error
    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const errMsg = errData?.error || 'Something went wrong';
      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'assistant', content: `❌ ${errMsg}` }
      ]);
      setLoading(false);
      return;
    }    
    // Read the complete Gemini response
    const aiResponse = await response.text();

    const trimmedResponse = aiResponse.trim();
    const codeMatch = trimmedResponse.match(/```(?:html|xml|markdown|css|javascript|ts|js)?\s*([\s\S]*?)```/i);
    const hasFileMarker = /---\s*FILE:\s*[^\r\n]+\s*---/i.test(trimmedResponse);
    const hasHtmlTags = /<html[\s>]|<body[\s>]|<div[\s>]|<section[\s>]|<header[\s>]|<!DOCTYPE/i.test(trimmedResponse);
    const isCodeResponse = Boolean(codeMatch) || hasFileMarker || hasHtmlTags;

    if (isCodeResponse) {
      let codeSoFar = trimmedResponse;
      if (codeMatch && codeMatch[1].trim()) {
        codeSoFar = codeMatch[1].trim();
      } else {
        codeSoFar = codeSoFar.replace(/^```[a-z0-9+#-]*\n?/i, '').replace(/\n?```$/i, '').trim();
      }

      setGeneratedCode(codeSoFar);

      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'assistant', content: 'Your website design is ready!' }
      ]);

      commitCodeToHistory(codeSoFar);
    } else {
      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'assistant', content: aiResponse }
      ]);
    }

    setLoading(false);
  }

  useEffect(() => {
    if (!frameId) return;

    const fetchFrameDetails = async () => {
      try {
        const result = await axios.get(`/api/frame?frameId=${frameId}&projectId=${projectId}`);
        console.log('Frame data:', result.data);
        console.log('Chat messages:', result.data.chatMessages);
        
        if (result.data.designCode) {
          setGeneratedCode(result.data.designCode);
          codeHistoryRef.current = [result.data.designCode];
          historyIndexRef.current = 0;
          setCanUndo(false);
          setCanRedo(false);
        }
        
        if (result.data.chatMessages && result.data.chatMessages.length > 0) {
          const parsedMessages = result.data.chatMessages.map((msg: Messages | string) => 
            typeof msg === 'string' ? JSON.parse(msg) : msg
          );
          console.log('Parsed messages:', parsedMessages);
          setMessages(parsedMessages);
          
          if (parsedMessages.length === 1 && parsedMessages[0].role === 'user' && !hasAutoGenerated.current) {
            console.log('Auto-generating code for message:', parsedMessages[0].content);
            hasAutoGenerated.current = true;
            SendMessage(parsedMessages[0].content, true, parsedMessages[0].image);
          }
        } else {
          setMessages([]);
        }
      } catch (error) {
        console.error('Error fetching frame details:', error);
      }
    };

    fetchFrameDetails();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [frameId, projectId]);

  const isInitialLoad = useRef(true);
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const SaveMessages = useCallback(async () => {
    if (!frameId || messages.length === 0) return;

    try {
      const response = await axios.post('/api/chats', {
        messages: messages,
        frameId: frameId
      });
      console.log('Messages saved:', response.data);
    } catch (error) {
      console.warn('Messages could not be saved:', error);
    }
  }, [frameId, messages]);
  
  useEffect(() => {
    if (isInitialLoad.current) {
      isInitialLoad.current = false;
      return;
    }
    
    if(messages.length > 0) {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
      
      saveTimeoutRef.current = setTimeout(() => {
        SaveMessages();
      }, 2000);
    }
    
    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
    };
  }, [messages, SaveMessages]);

  const isInitialCodeLoad = useRef(true);
  const codeSaveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const SaveDesignCode = useCallback(async () => {
    if (!frameId || !projectId) return;

    try {
      const response = await axios.put('/api/frame', {
        frameId: frameId,
        projectId: projectId,
        designCode: generatedCode
      });
      console.log('Design code saved:', response.data);
    } catch (error) {
      console.error('Error saving design code:', error);
    }
  }, [frameId, projectId, generatedCode]);

  useEffect(() => {
    if (isInitialCodeLoad.current) {
      isInitialCodeLoad.current = false;
      return;
    }

    if (generatedCode) {
      if (codeSaveTimeoutRef.current) {
        clearTimeout(codeSaveTimeoutRef.current);
      }

      codeSaveTimeoutRef.current = setTimeout(() => {
        SaveDesignCode();
      }, 2000);
    }

    return () => {
      if (codeSaveTimeoutRef.current) {
        clearTimeout(codeSaveTimeoutRef.current);
      }
    };
  }, [generatedCode, SaveDesignCode]);

return (
  <div className="relative flex h-screen min-h-0 min-w-0 flex-col overflow-hidden bg-white">
    <div className="shrink-0">
      <PlaygroundHeader onSettingsToggle={() => setShowSettings(prev => !prev)} currentDesignCode={generatedCode} />
    </div>
    <div className="relative flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden md:flex-row">
        <ChatSection Messages={messages} 
        onSend={(input: string) => SendMessage(input)} 
        loading={loading} />
        <WebsiteDesign 
          generatedCode={generatedCode.replace(/```html/g, '').replace(/```/g, '')}
          onCodeChange={(newCode) => setGeneratedCode(newCode)}
          onCommitCodeChange={(newCode) => commitCodeToHistory(newCode)}
          canUndo={canUndo}
          canRedo={canRedo}
          onUndo={handleUndo}
          onRedo={handleRedo}
        />
    </div>

    {showSettings && (
      <Settings
        selectedModel={selectedModel}
        onSelectModel={setSelectedModel}
        selectedTheme={selectedTheme}
        onSelectTheme={setSelectedTheme}
        onClose={() => setShowSettings(false)}
      />
    )}
  </div>
)
}

export default PlaygroundPage
