"use client";
import React, { useEffect, useState, useRef, useCallback } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import axios from 'axios';
import PlaygroundHeader from '../_components/PlaygroundHeader';
import ChatSection from '../_components/ChatSection';
import WebsiteDesign from '../_components/WebsiteDesign';
import Settings from '../_components/Settings';
import { parseAIResponseToPatch } from '@/lib/aiResponseSchema';
import { validateAndApplyPatch } from '@/lib/aiPatchEngine';
import { parseMultiFiles, serializeFiles } from '@/lib/fileTree';

export type Frame = {
  projectId: string;
  frameId: string;
  chatMessages: Messages[];
  designCode: string;
};

export type Messages = {
  role: string;
  content: string;
  image?: string;
};

export type AIState = 'IDLE' | 'GENERATING' | 'STREAMING' | 'COMPLETED' | 'ERROR' | 'CANCELLED';

const Prompt = `User Request: {user_input}

Primary Theme Color: {theme_color}

INSTRUCTIONS FOR CODE GENERATION:
1. Generate ONLY the standalone end-user website/application described in the request (e.g. landing page, SaaS dashboard, e-commerce store, portfolio).
2. DEFAULT THEME: Always generate the website with a clean, modern, high-contrast LIGHT THEME by default (white or light-slate backgrounds bg-white / bg-slate-50, text-slate-900 readability, crisp light card containers) UNLESS the user explicitly specifies "dark mode" or "dark theme" in their prompt.
3. DO NOT generate any host IDE wrapper, Playground toolbar, 'AiSite.builder' logo, 'AI ASSISTANT' panel, or prompt chat sidebar.
4. The main file 'index.html' must start directly with standard HTML5 <!DOCTYPE html><html lang="en"> containing only the target product website.
5. Always include a primary 'index.html' file.
6. Use real high-resolution Unsplash image URLs.
7. Format every file strictly using:
--- FILE: path/to/file.ext ---
<file contents>`;

function PlaygroundPage() {
  const { projectId } = useParams();
  const searchParams = useSearchParams();
  const frameId = searchParams.get('frameId');
  const [loading, setLoading] = useState(false);
  const [aiState, setAiState] = useState<AIState>('IDLE');
  const [messages, setMessages] = useState<Messages[]>([]);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const hasAutoGenerated = useRef(false);
  const [selectedModel, setSelectedModel] = useState('gemini-3.5-flash');
  const [selectedTheme, setSelectedTheme] = useState('blue');
  const [showSettings, setShowSettings] = useState(false);

  // ---- Controlled Header & Workspace Layout State ----
  const [activeTab, setActiveTab] = useState<"preview" | "code" | "split" | "api" | "context">("preview");
  const [device, setDevice] = useState<"desktop" | "tablet" | "mobile">("desktop");
  const [activePreviewPage, setActivePreviewPage] = useState<string>("index.html");
  const [htmlPages, setHtmlPages] = useState<{ path: string; label: string }[]>([]);
  const [isInspectMode, setIsInspectMode] = useState<boolean>(false);
  const [showBrowserDrawer, setShowBrowserDrawer] = useState<boolean>(false);
  const [openModalName, setOpenModalName] = useState<string | null>(null);
  const [showExportModal, setShowExportModal] = useState<boolean>(false);
  const [showDeployModal, setShowDeployModal] = useState<boolean>(false);

  // ---- Undo / Redo history for generatedCode ----
  const codeHistoryRef = useRef<string[]>(['']);
  const historyIndexRef = useRef<number>(0);
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);
  const abortControllerRef = useRef<AbortController | null>(null);

  const commitCodeToHistory = (code: string) => {
    if (codeHistoryRef.current[historyIndexRef.current] === code) return;
    codeHistoryRef.current = codeHistoryRef.current.slice(0, historyIndexRef.current + 1);
    codeHistoryRef.current.push(code);
    historyIndexRef.current = codeHistoryRef.current.length - 1;
    setCanUndo(historyIndexRef.current > 0);
    setCanRedo(false);
  };

  const handleUndo = () => {
    if (historyIndexRef.current <= 0) return;
    historyIndexRef.current -= 1;
    setGeneratedCode(codeHistoryRef.current[historyIndexRef.current]);
    setCanUndo(historyIndexRef.current > 0);
    setCanRedo(true);
  };

  const handleRedo = () => {
    if (historyIndexRef.current >= codeHistoryRef.current.length - 1) return;
    historyIndexRef.current += 1;
    setGeneratedCode(codeHistoryRef.current[historyIndexRef.current]);
    setCanUndo(true);
    setCanRedo(historyIndexRef.current < codeHistoryRef.current.length - 1);
  };

  const cancelGeneration = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      setAiState('CANCELLED');
      setLoading(false);
    }
  };

  const SendMessage = async (message: string, skipAddUserMessage: boolean = false, image?: string) => {
    setLoading(true);
    setAiState('GENERATING');

    if (!skipAddUserMessage) {
      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'user', content: message }
      ]);
    }

    const messagesWithoutLast = skipAddUserMessage ? messages.slice(0, -1) : messages;
    const finalPrompt = Prompt?.replace('{user_input}', message).replace('{theme_color}', selectedTheme);
    const formattedMessages = [
      ...messagesWithoutLast,
      { role: 'user', content: finalPrompt }
    ];

    abortControllerRef.current = new AbortController();

    try {
      const response = await fetch('/api/ai-model', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        signal: abortControllerRef.current.signal,
        body: JSON.stringify({
          messages: formattedMessages,
          modelName: selectedModel,
          image: image || undefined,
          mode: generatedCode ? 'patch' : 'full',
          currentFilesSummary: generatedCode ? generatedCode.slice(0, 1500) : undefined,
        }),
      });

      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        const errMsg = errData?.error || 'Something went wrong';
        setMessages((prev: Messages[]) => [
          ...prev,
          { role: 'assistant', content: `❌ ${errMsg}` }
        ]);
        setAiState('ERROR');
        setLoading(false);
        return;
      }

      const reader = response.body?.getReader();
      if (!reader) {
        throw new Error('Response body is not readable');
      }

      setAiState('STREAMING');
      const decoder = new TextDecoder();
      let streamedText = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        streamedText += chunk;

        // Progressively update generatedCode preview if text resembles direct code or files
        if (streamedText.includes('--- FILE:') || streamedText.includes('<html')) {
          const currentParsed = parseMultiFiles(streamedText);
          const serialized = serializeFiles(currentParsed);
          if (serialized) {
            setGeneratedCode(serialized);
          }
        }
      }

      const trimmedResponse = streamedText.trim();
      const currentFilesMap = parseMultiFiles(generatedCode);
      const patchPayload = parseAIResponseToPatch(trimmedResponse, currentFilesMap);

      if (patchPayload.type === 'patch' && patchPayload.operations && patchPayload.operations.length > 0) {
        const patchResult = validateAndApplyPatch(currentFilesMap, patchPayload);

        if (patchResult.success) {
          const newCodeStr = serializeFiles(patchResult.files);
          setGeneratedCode(newCodeStr);
          commitCodeToHistory(newCodeStr);
          setMessages((prev: Messages[]) => [
            ...prev,
            { role: 'assistant', content: patchPayload.summary || 'Applied targeted AI edits successfully!' }
          ]);
        } else {
          // If targeted patch failed, attempt fallback full file parsing
          const fallbackFiles = parseMultiFiles(trimmedResponse);
          const fallbackSerialized = serializeFiles(fallbackFiles);
          if (fallbackSerialized) {
            setGeneratedCode(fallbackSerialized);
            commitCodeToHistory(fallbackSerialized);
            setMessages((prev: Messages[]) => [
              ...prev,
              { role: 'assistant', content: 'Updated code using full file fallback.' }
            ]);
          } else {
            setMessages((prev: Messages[]) => [
              ...prev,
              { role: 'assistant', content: `⚠️ Patch failed: ${patchResult.errors.join(', ')}` }
            ]);
          }
        }
      } else {
        // Standard full file generation or fallback text
        const codeMatch = trimmedResponse.match(/```(?:html|xml|markdown|css|javascript|ts|js)?\s*([\s\S]*?)```/i);
        const hasFileMarker = /---\s*FILE:\s*[^\r\n]+\s*---/i.test(trimmedResponse);
        const hasHtmlTags = /<html[\s>]|<body[\s>]|<div[\s>]|<section[\s>]|<header[\s>]|<!DOCTYPE/i.test(trimmedResponse);
        const isCodeResponse = Boolean(codeMatch) || hasFileMarker || hasHtmlTags;

        if (isCodeResponse) {
          let codeSoFar = trimmedResponse;
          if (codeMatch && codeMatch[1].trim()) {
            codeSoFar = codeMatch[1].trim();
          } else {
            codeSoFar = codeSoFar.replace(/^```[a-z0-9+#-]*\n?/i, '').replace(/\n?```$/i, '').trim();
          }

          setGeneratedCode(codeSoFar);
          commitCodeToHistory(codeSoFar);
          setMessages((prev: Messages[]) => [
            ...prev,
            { role: 'assistant', content: 'Your website design is ready!' }
          ]);
        } else {
          setMessages((prev: Messages[]) => [
            ...prev,
            { role: 'assistant', content: trimmedResponse }
          ]);
        }
      }

      setAiState('COMPLETED');
    } catch (err: unknown) {
      if ((err as Error)?.name === 'AbortError') {
        console.log('Generation cancelled by user');
        setAiState('CANCELLED');
      } else {
        console.error('Streaming error:', err);
        const errMsg = err instanceof Error ? err.message : 'Streaming error occurred';
        setMessages((prev: Messages[]) => [
          ...prev,
          { role: 'assistant', content: `❌ ${errMsg}` }
        ]);
        setAiState('ERROR');
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!frameId) return;

    const fetchFrameDetails = async () => {
      try {
        const result = await axios.get(`/api/frame?frameId=${frameId}&projectId=${projectId}`);
        if (result.data.designCode) {
          setGeneratedCode(result.data.designCode);
          codeHistoryRef.current = [result.data.designCode];
          historyIndexRef.current = 0;
          setCanUndo(false);
          setCanRedo(false);
        }

        if (result.data.chatMessages && result.data.chatMessages.length > 0) {
          const parsedMessages = result.data.chatMessages.map((msg: Messages | string) =>
            typeof msg === 'string' ? JSON.parse(msg) : msg
          );
          setMessages(parsedMessages);

          if (parsedMessages.length === 1 && parsedMessages[0].role === 'user' && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            SendMessage(parsedMessages[0].content, true, parsedMessages[0].image);
          }
        } else {
          setMessages([]);
        }
      } catch (error) {
        console.error('Error fetching frame details:', error);
      }
    };

    fetchFrameDetails();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [frameId, projectId]);

  const isInitialLoad = useRef(true);
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const SaveMessages = useCallback(async () => {
    if (!frameId || messages.length === 0) return;

    try {
      await axios.post('/api/chats', {
        messages: messages,
        frameId: frameId
      });
    } catch (error) {
      console.warn('Messages could not be saved:', error);
    }
  }, [frameId, messages]);

  useEffect(() => {
    if (isInitialLoad.current) {
      isInitialLoad.current = false;
      return;
    }

    if (messages.length > 0) {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }

      saveTimeoutRef.current = setTimeout(() => {
        SaveMessages();
      }, 2000);
    }

    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
    };
  }, [messages, SaveMessages]);

  const isInitialCodeLoad = useRef(true);
  const codeSaveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const SaveDesignCode = useCallback(async () => {
    if (!frameId || !projectId) return;

    try {
      await axios.put('/api/frame', {
        frameId: frameId,
        projectId: projectId,
        designCode: generatedCode
      });
    } catch (error) {
      console.error('Error saving design code:', error);
    }
  }, [frameId, projectId, generatedCode]);

  useEffect(() => {
    if (isInitialCodeLoad.current) {
      isInitialCodeLoad.current = false;
      return;
    }

    if (generatedCode) {
      if (codeSaveTimeoutRef.current) {
        clearTimeout(codeSaveTimeoutRef.current);
      }

      codeSaveTimeoutRef.current = setTimeout(() => {
        SaveDesignCode();
      }, 2000);
    }

    return () => {
      if (codeSaveTimeoutRef.current) {
        clearTimeout(codeSaveTimeoutRef.current);
      }
    };
  }, [generatedCode, SaveDesignCode]);

  return (
    <div className="relative flex h-screen min-h-0 min-w-0 flex-col md:flex-row overflow-hidden bg-slate-100 text-slate-900">
      <PlaygroundHeader
        onSettingsToggle={() => setShowSettings((prev) => !prev)}
        currentDesignCode={generatedCode}
        activeTab={activeTab}
        onTabChange={setActiveTab}
        device={device}
        onDeviceChange={setDevice}
        htmlPages={htmlPages}
        activePreviewPage={activePreviewPage}
        onPageChange={setActivePreviewPage}
        canUndo={canUndo}
        canRedo={canRedo}
        onUndo={handleUndo}
        onRedo={handleRedo}
        isInspectMode={isInspectMode}
        onInspectToggle={() => setIsInspectMode((prev) => !prev)}
        showBrowserDrawer={showBrowserDrawer}
        onBrowserDrawerToggle={() => setShowBrowserDrawer((prev) => !prev)}
        onExportZip={() => setShowExportModal(true)}
        onLiveDeploy={() => setShowDeployModal(true)}
        onOpenModal={(modalName) => setOpenModalName(modalName)}
      />
      <div className="relative flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden md:flex-row">
        <ChatSection
          Messages={messages}
          onSend={(input: string) => SendMessage(input)}
          loading={loading}
        />
        <WebsiteDesign
          generatedCode={generatedCode.replace(/```html/g, '').replace(/```/g, '')}
          onCodeChange={(newCode) => setGeneratedCode(newCode)}
          onCommitCodeChange={(newCode) => commitCodeToHistory(newCode)}
          canUndo={canUndo}
          canRedo={canRedo}
          onUndo={handleUndo}
          onRedo={handleRedo}
          activeTab={activeTab}
          device={device}
          activePreviewPage={activePreviewPage}
          onPageChange={setActivePreviewPage}
          onHtmlPagesDetected={setHtmlPages}
          isInspectMode={isInspectMode}
          showBrowserDrawer={showBrowserDrawer}
          showExportModal={showExportModal}
          onExportModalClose={() => setShowExportModal(false)}
          showDeployModal={showDeployModal}
          onDeployModalClose={() => setShowDeployModal(false)}
          openModalName={openModalName}
          onCloseModal={() => setOpenModalName(null)}
        />
      </div>

      {showSettings && (
        <Settings
          selectedModel={selectedModel}
          onSelectModel={setSelectedModel}
          selectedTheme={selectedTheme}
          onSelectTheme={setSelectedTheme}
          onClose={() => setShowSettings(false)}
        />
      )}
    </div>
  );
}

export default PlaygroundPage;
