"use client"
import React, { useEffect, useState, useRef, useCallback } from 'react'
import { useParams, useSearchParams } from 'next/navigation'
import axios from 'axios'
import PlaygroundHeader from '../_components/PlaygroundHeader'
import ChatSection from '../_components/ChatSection'
import WebsiteDesign from '../_components/WebsiteDesign'
import Settings from '../_components/Settings'


export type Frame = {
  projectId: string;
  frameId: string;
  chatMessages: Messages[];
  designCode: string;
}
export type Messages = {
  role: string;
  content: string;
  image?: string;
}


const Prompt = `User Request: {user_input}

Primary Theme Color: {theme_color}

INSTRUCTIONS FOR CODE GENERATION:
1. Generate a complete, standalone, production-grade web application for the user's requested business/product using HTML, Tailwind CSS, JavaScript, and asset files.
2. Build ONLY the end-user website/application described in the request (e.g. landing page, SaaS dashboard, e-commerce store, portfolio).
3. The main file 'index.html' must start directly with <!DOCTYPE html><html lang="en"> and contain the complete markup (header, hero, sections, footer) of the end-user website.
4. Always include a primary 'index.html' file.
5. Use real high-resolution Unsplash image URLs (e.g. https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80 for tech, https://images.unsplash.com/photo-1523275335684-37898b6baf30 for products, https://images.unsplash.com/photo-1534528741775-53994a69daeb for avatars).
6. Format every file strictly using:
--- FILE: path/to/file.ext ---
<file contents>
--- FILE: css/styles.css ---
<file contents>
--- FILE: js/main.js ---
<file contents>`;


function PlaygroundPage() {
  const { projectId } = useParams();
  const searchParams = useSearchParams();
  const frameId = searchParams.get('frameId');
  const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Messages[]>([]);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const hasAutoGenerated = useRef(false);
  const [selectedModel, setSelectedModel] = useState('gemini-3.6-flash');
  const [selectedTheme, setSelectedTheme] = useState('blue');
  const [showSettings, setShowSettings] = useState(false);

  // ---- Controlled Header & Workspace Layout State ----
  const [activeTab, setActiveTab] = useState<"preview" | "code" | "split" | "api" | "context">("preview");
  const [device, setDevice] = useState<"desktop" | "tablet" | "mobile">("desktop");
  const [activePreviewPage, setActivePreviewPage] = useState<string>("index.html");
  const [htmlPages, setHtmlPages] = useState<{ path: string; label: string }[]>([]);
  const [isInspectMode, setIsInspectMode] = useState<boolean>(false);
  const [showBrowserDrawer, setShowBrowserDrawer] = useState<boolean>(false);
  const [openModalName, setOpenModalName] = useState<string | null>(null);
  const [showExportModal, setShowExportModal] = useState<boolean>(false);
  const [showDeployModal, setShowDeployModal] = useState<boolean>(false);

  // ---- Undo / Redo history for generatedCode ----
  const codeHistoryRef = useRef<string[]>(['']);
  const historyIndexRef = useRef<number>(0);
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);

  const commitCodeToHistory = (code: string) => {
    if (codeHistoryRef.current[historyIndexRef.current] === code) return;
    codeHistoryRef.current = codeHistoryRef.current.slice(0, historyIndexRef.current + 1);
    codeHistoryRef.current.push(code);
    historyIndexRef.current = codeHistoryRef.current.length - 1;
    setCanUndo(historyIndexRef.current > 0);
    setCanRedo(false);
  };

  const handleUndo = () => {
    if (historyIndexRef.current <= 0) return;
    historyIndexRef.current -= 1;
    setGeneratedCode(codeHistoryRef.current[historyIndexRef.current]);
    setCanUndo(historyIndexRef.current > 0);
    setCanRedo(true);
  };

  const handleRedo = () => {
    if (historyIndexRef.current >= codeHistoryRef.current.length - 1) return;
    historyIndexRef.current += 1;
    setGeneratedCode(codeHistoryRef.current[historyIndexRef.current]);
    setCanUndo(true);
    setCanRedo(historyIndexRef.current < codeHistoryRef.current.length - 1);
  };
  
  const SendMessage = async(message: string, skipAddUserMessage: boolean = false, image?: string) => {
    setLoading(true);
    setGeneratedCode(''); // Reset generated code for new generation

    //Add User Message (if not already in messages)
    if(!skipAddUserMessage) {
      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'user', content: message }]);
    }

    // Build messages array: send full history without the last message, then add it with the prompt
    const messagesWithoutLast = skipAddUserMessage ? messages.slice(0, -1) : messages;
    const finalPrompt = Prompt?.replace('{user_input}', message).replace('{theme_color}', selectedTheme);
    const formattedMessages = [
      ...messagesWithoutLast,
      { role: 'user', content: finalPrompt }
    ];

    const response = await fetch('/api/ai-model', {
      method:'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body:JSON.stringify({
        messages: formattedMessages,
        modelName: selectedModel,
        image: image || undefined
      })
    });

    // Check if credits ran out (403) or other error
    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const errMsg = errData?.error || 'Something went wrong';
      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'assistant', content: `❌ ${errMsg}` }
      ]);
      setLoading(false);
      return;
    }    
    // Read the complete Gemini response
    const aiResponse = await response.text();

    const trimmedResponse = aiResponse.trim();
    const codeMatch = trimmedResponse.match(/```(?:html|xml|markdown|css|javascript|ts|js)?\s*([\s\S]*?)```/i);
    const hasFileMarker = /---\s*FILE:\s*[^\r\n]+\s*---/i.test(trimmedResponse);
    const hasHtmlTags = /<html[\s>]|<body[\s>]|<div[\s>]|<section[\s>]|<header[\s>]|<!DOCTYPE/i.test(trimmedResponse);
    const isCodeResponse = Boolean(codeMatch) || hasFileMarker || hasHtmlTags;

    if (isCodeResponse) {
      let codeSoFar = trimmedResponse;
      if (codeMatch && codeMatch[1].trim()) {
        codeSoFar = codeMatch[1].trim();
      } else {
        codeSoFar = codeSoFar.replace(/^```[a-z0-9+#-]*\n?/i, '').replace(/\n?```$/i, '').trim();
      }

      setGeneratedCode(codeSoFar);

      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'assistant', content: 'Your website design is ready!' }
      ]);

      commitCodeToHistory(codeSoFar);
    } else {
      setMessages((prev: Messages[]) => [
        ...prev,
        { role: 'assistant', content: aiResponse }
      ]);
    }

    setLoading(false);
  }

  useEffect(() => {
    if (!frameId) return;

    const fetchFrameDetails = async () => {
      try {
        const result = await axios.get(`/api/frame?frameId=${frameId}&projectId=${projectId}`);
        console.log('Frame data:', result.data);
        console.log('Chat messages:', result.data.chatMessages);
        
        if (result.data.designCode) {
          setGeneratedCode(result.data.designCode);
          codeHistoryRef.current = [result.data.designCode];
          historyIndexRef.current = 0;
          setCanUndo(false);
          setCanRedo(false);
        }
        
        if (result.data.chatMessages && result.data.chatMessages.length > 0) {
          const parsedMessages = result.data.chatMessages.map((msg: Messages | string) => 
            typeof msg === 'string' ? JSON.parse(msg) : msg
          );
          console.log('Parsed messages:', parsedMessages);
          setMessages(parsedMessages);
          
          if (parsedMessages.length === 1 && parsedMessages[0].role === 'user' && !hasAutoGenerated.current) {
            console.log('Auto-generating code for message:', parsedMessages[0].content);
            hasAutoGenerated.current = true;
            SendMessage(parsedMessages[0].content, true, parsedMessages[0].image);
          }
        } else {
          setMessages([]);
        }
      } catch (error) {
        console.error('Error fetching frame details:', error);
      }
    };

    fetchFrameDetails();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [frameId, projectId]);

  const isInitialLoad = useRef(true);
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const SaveMessages = useCallback(async () => {
    if (!frameId || messages.length === 0) return;

    try {
      const response = await axios.post('/api/chats', {
        messages: messages,
        frameId: frameId
      });
      console.log('Messages saved:', response.data);
    } catch (error) {
      console.warn('Messages could not be saved:', error);
    }
  }, [frameId, messages]);
  
  useEffect(() => {
    if (isInitialLoad.current) {
      isInitialLoad.current = false;
      return;
    }
    
    if(messages.length > 0) {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
      
      saveTimeoutRef.current = setTimeout(() => {
        SaveMessages();
      }, 2000);
    }
    
    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
    };
  }, [messages, SaveMessages]);

  const isInitialCodeLoad = useRef(true);
  const codeSaveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const SaveDesignCode = useCallback(async () => {
    if (!frameId || !projectId) return;

    try {
      const response = await axios.put('/api/frame', {
        frameId: frameId,
        projectId: projectId,
        designCode: generatedCode
      });
      console.log('Design code saved:', response.data);
    } catch (error) {
      console.error('Error saving design code:', error);
    }
  }, [frameId, projectId, generatedCode]);

  useEffect(() => {
    if (isInitialCodeLoad.current) {
      isInitialCodeLoad.current = false;
      return;
    }

    if (generatedCode) {
      if (codeSaveTimeoutRef.current) {
        clearTimeout(codeSaveTimeoutRef.current);
      }

      codeSaveTimeoutRef.current = setTimeout(() => {
        SaveDesignCode();
      }, 2000);
    }

    return () => {
      if (codeSaveTimeoutRef.current) {
        clearTimeout(codeSaveTimeoutRef.current);
      }
    };
  }, [generatedCode, SaveDesignCode]);

return (
  <div className="relative flex h-screen min-h-0 min-w-0 flex-col overflow-hidden bg-slate-950">
    <PlaygroundHeader
      onSettingsToggle={() => setShowSettings((prev) => !prev)}
      currentDesignCode={generatedCode}
      activeTab={activeTab}
      onTabChange={setActiveTab}
      device={device}
      onDeviceChange={setDevice}
      htmlPages={htmlPages}
      activePreviewPage={activePreviewPage}
      onPageChange={setActivePreviewPage}
      canUndo={canUndo}
      canRedo={canRedo}
      onUndo={handleUndo}
      onRedo={handleRedo}
      isInspectMode={isInspectMode}
      onInspectToggle={() => setIsInspectMode((prev) => !prev)}
      showBrowserDrawer={showBrowserDrawer}
      onBrowserDrawerToggle={() => setShowBrowserDrawer((prev) => !prev)}
      onExportZip={() => setShowExportModal(true)}
      onLiveDeploy={() => setShowDeployModal(true)}
      onOpenModal={(modalName) => setOpenModalName(modalName)}
    />
    <div className="relative flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden md:flex-row">
        <ChatSection Messages={messages} 
        onSend={(input: string) => SendMessage(input)} 
        loading={loading} />
        <WebsiteDesign 
          generatedCode={generatedCode.replace(/```html/g, '').replace(/```/g, '')}
          onCodeChange={(newCode) => setGeneratedCode(newCode)}
          onCommitCodeChange={(newCode) => commitCodeToHistory(newCode)}
          canUndo={canUndo}
          canRedo={canRedo}
          onUndo={handleUndo}
          onRedo={handleRedo}
          activeTab={activeTab}
          device={device}
          activePreviewPage={activePreviewPage}
          onPageChange={setActivePreviewPage}
          onHtmlPagesDetected={setHtmlPages}
          isInspectMode={isInspectMode}
          showBrowserDrawer={showBrowserDrawer}
          showExportModal={showExportModal}
          onExportModalClose={() => setShowExportModal(false)}
          showDeployModal={showDeployModal}
          onDeployModalClose={() => setShowDeployModal(false)}
          openModalName={openModalName}
          onCloseModal={() => setOpenModalName(null)}
        />
    </div>

    {showSettings && (
      <Settings
        selectedModel={selectedModel}
        onSelectModel={setSelectedModel}
        selectedTheme={selectedTheme}
        onSelectTheme={setSelectedTheme}
        onClose={() => setShowSettings(false)}
      />
    )}
  </div>
)
}

export default PlaygroundPage
